# Code generated by `typeddictgen`. DO NOT EDIT.
"""AuthenticationV1TokenRequestDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1TokenRequestSpecDict, V1TokenRequestStatusDict

AuthenticationV1TokenRequestDict = TypedDict(
    "AuthenticationV1TokenRequestDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1TokenRequestSpecDict,
        "status": V1TokenRequestStatusDict,
    },
    total=False,
)
