# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EndpointPortDict generated type."""
from typing import TypedDict

CoreV1EndpointPortDict = TypedDict(
    "CoreV1EndpointPortDict",
    {
        "appProtocol": str,
        "name": str,
        "port": int,
        "protocol": str,
    },
    total=False,
)
