# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EventSeriesDict generated type."""
import datetime
from typing import TypedDict

CoreV1EventSeriesDict = TypedDict(
    "CoreV1EventSeriesDict",
    {
        "count": int,
        "lastObservedTime": datetime.datetime,
    },
    total=False,
)
