# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EventListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import CoreV1EventDict, V1ListMetaDict

CoreV1EventListDict = TypedDict(
    "CoreV1EventListDict",
    {
        "apiVersion": str,
        "items": List[CoreV1EventDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
