# Code generated by `typeddictgen`. DO NOT EDIT.
"""CoreV1EventDict generated type."""
import datetime
from typing import TypedDict

from kubernetes_typed.client import CoreV1EventSeriesDict, V1EventSourceDict, V1ObjectMetaDict, V1ObjectReferenceDict

CoreV1EventDict = TypedDict(
    "CoreV1EventDict",
    {
        "action": str,
        "apiVersion": str,
        "count": int,
        "eventTime": datetime.datetime,
        "firstTimestamp": datetime.datetime,
        "involvedObject": V1ObjectReferenceDict,
        "kind": str,
        "lastTimestamp": datetime.datetime,
        "message": str,
        "metadata": V1ObjectMetaDict,
        "reason": str,
        "related": V1ObjectReferenceDict,
        "reportingComponent": str,
        "reportingInstance": str,
        "series": CoreV1EventSeriesDict,
        "source": V1EventSourceDict,
        "type": str,
    },
    total=False,
)
