# Code generated by `typeddictgen`. DO NOT EDIT.
"""DiscoveryV1EndpointPortDict generated type."""
from typing import TypedDict

DiscoveryV1EndpointPortDict = TypedDict(
    "DiscoveryV1EndpointPortDict",
    {
        "appProtocol": str,
        "name": str,
        "port": int,
        "protocol": str,
    },
    total=False,
)
