# Code generated by `typeddictgen`. DO NOT EDIT.
"""EventsV1EventSeriesDict generated type."""
import datetime
from typing import TypedDict

EventsV1EventSeriesDict = TypedDict(
    "EventsV1EventSeriesDict",
    {
        "count": int,
        "lastObservedTime": datetime.datetime,
    },
    total=False,
)
