# Code generated by `typeddictgen`. DO NOT EDIT.
"""EventsV1EventListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import EventsV1EventDict, V1ListMetaDict

EventsV1EventListDict = TypedDict(
    "EventsV1EventListDict",
    {
        "apiVersion": str,
        "items": List[EventsV1EventDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
