# Code generated by `typeddictgen`. DO NOT EDIT.
"""StorageV1TokenRequestDict generated type."""
from typing import TypedDict

StorageV1TokenRequestDict = TypedDict(
    "StorageV1TokenRequestDict",
    {
        "audience": str,
        "expirationSeconds": int,
    },
    total=False,
)
