# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1CronJobSpecDict, V1CronJobStatusDict, V1ObjectMetaDict

V1CronJobDict = TypedDict(
    "V1CronJobDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1CronJobSpecDict,
        "status": V1CronJobStatusDict,
    },
    total=False,
)
