# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1CertificateSigningRequestConditionDict

V1CertificateSigningRequestStatusDict = TypedDict(
    "V1CertificateSigningRequestStatusDict",
    {
        "certificate": str,
        "conditions": List[V1CertificateSigningRequestConditionDict],
    },
    total=False,
)
