# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CertificateSigningRequestSpecDict generated type."""
from typing import TypedDict, Dict, List

V1CertificateSigningRequestSpecDict = TypedDict(
    "V1CertificateSigningRequestSpecDict",
    {
        "expirationSeconds": int,
        "extra": Dict[str, List[str]],
        "groups": List[str],
        "request": str,
        "signerName": str,
        "uid": str,
        "usages": List[str],
        "username": str,
    },
    total=False,
)
