# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1JobTemplateSpecDict

V1CronJobSpecDict = TypedDict(
    "V1CronJobSpecDict",
    {
        "concurrencyPolicy": str,
        "failedJobsHistoryLimit": int,
        "jobTemplate": V1JobTemplateSpecDict,
        "schedule": str,
        "startingDeadlineSeconds": int,
        "successfulJobsHistoryLimit": int,
        "suspend": bool,
    },
    total=False,
)
