# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CronJobStatusDict generated type."""
import datetime
from typing import TypedDict, List

from kubernetes_typed.client import V1ObjectReferenceDict

V1CronJobStatusDict = TypedDict(
    "V1CronJobStatusDict",
    {
        "active": List[V1ObjectReferenceDict],
        "lastScheduleTime": datetime.datetime,
        "lastSuccessfulTime": datetime.datetime,
    },
    total=False,
)
