# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointDict generated type."""
from typing import TypedDict, Dict, List

from kubernetes_typed.client import V1EndpointConditionsDict, V1EndpointHintsDict, V1ObjectReferenceDict

V1EndpointDict = TypedDict(
    "V1EndpointDict",
    {
        "addresses": List[str],
        "conditions": V1EndpointConditionsDict,
        "deprecatedTopology": Dict[str, str],
        "hints": V1EndpointHintsDict,
        "hostname": str,
        "nodeName": str,
        "targetRef": V1ObjectReferenceDict,
        "zone": str,
    },
    total=False,
)
