# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EphemeralVolumeSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1PersistentVolumeClaimTemplateDict

V1EphemeralVolumeSourceDict = TypedDict(
    "V1EphemeralVolumeSourceDict",
    {
        "volumeClaimTemplate": V1PersistentVolumeClaimTemplateDict,
    },
    total=False,
)
