# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointHintsDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ForZoneDict

V1EndpointHintsDict = TypedDict(
    "V1EndpointHintsDict",
    {
        "forZones": List[V1ForZoneDict],
    },
    total=False,
)
