# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointSliceDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import DiscoveryV1EndpointPortDict, V1EndpointDict, V1ObjectMetaDict

V1EndpointSliceDict = TypedDict(
    "V1EndpointSliceDict",
    {
        "addressType": str,
        "apiVersion": str,
        "endpoints": List[V1EndpointDict],
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "ports": List[DiscoveryV1EndpointPortDict],
    },
    total=False,
)
