# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointConditionsDict generated type."""
from typing import TypedDict

V1EndpointConditionsDict = TypedDict(
    "V1EndpointConditionsDict",
    {
        "ready": bool,
        "serving": bool,
        "terminating": bool,
    },
    total=False,
)
