# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointSliceListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1EndpointSliceDict, V1ListMetaDict

V1EndpointSliceListDict = TypedDict(
    "V1EndpointSliceListDict",
    {
        "apiVersion": str,
        "items": List[V1EndpointSliceDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
