# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ForZoneDict generated type."""
from typing import TypedDict

V1ForZoneDict = TypedDict(
    "V1ForZoneDict",
    {
        "name": str,
    },
    total=False,
)
