# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GRPCActionDict generated type."""
from typing import TypedDict

V1GRPCActionDict = TypedDict(
    "V1GRPCActionDict",
    {
        "port": int,
        "service": str,
    },
    total=False,
)
