# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HTTPIngressPathDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1IngressBackendDict

V1HTTPIngressPathDict = TypedDict(
    "V1HTTPIngressPathDict",
    {
        "backend": V1IngressBackendDict,
        "path": str,
        "pathType": str,
    },
    total=False,
)
