# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassParametersReferenceDict generated type."""
from typing import TypedDict

V1IngressClassParametersReferenceDict = TypedDict(
    "V1IngressClassParametersReferenceDict",
    {
        "apiGroup": str,
        "kind": str,
        "name": str,
        "namespace": str,
        "scope": str,
    },
    total=False,
)
