# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressRuleDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1HTTPIngressRuleValueDict

V1IngressRuleDict = TypedDict(
    "V1IngressRuleDict",
    {
        "host": str,
        "http": V1HTTPIngressRuleValueDict,
    },
    total=False,
)
