# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressServiceBackendDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ServiceBackendPortDict

V1IngressServiceBackendDict = TypedDict(
    "V1IngressServiceBackendDict",
    {
        "name": str,
        "port": V1ServiceBackendPortDict,
    },
    total=False,
)
