# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1IngressClassDict, V1ListMetaDict

V1IngressClassListDict = TypedDict(
    "V1IngressClassListDict",
    {
        "apiVersion": str,
        "items": List[V1IngressClassDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
