# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressBackendDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1IngressServiceBackendDict, V1TypedLocalObjectReferenceDict

V1IngressBackendDict = TypedDict(
    "V1IngressBackendDict",
    {
        "resource": V1TypedLocalObjectReferenceDict,
        "service": V1IngressServiceBackendDict,
    },
    total=False,
)
