# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressTLSDict generated type."""
from typing import TypedDict, List

V1IngressTLSDict = TypedDict(
    "V1IngressTLSDict",
    {
        "hosts": List[str],
        "secretName": str,
    },
    total=False,
)
