# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressClassDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1IngressClassSpecDict, V1ObjectMetaDict

V1IngressClassDict = TypedDict(
    "V1IngressClassDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1IngressClassSpecDict,
    },
    total=False,
)
