# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1IngressBackendDict, V1IngressRuleDict, V1IngressTLSDict

V1IngressSpecDict = TypedDict(
    "V1IngressSpecDict",
    {
        "defaultBackend": V1IngressBackendDict,
        "ingressClassName": str,
        "rules": List[V1IngressRuleDict],
        "tls": List[V1IngressTLSDict],
    },
    total=False,
)
