# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1IngressSpecDict, V1IngressStatusDict, V1ObjectMetaDict

V1IngressDict = TypedDict(
    "V1IngressDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1IngressSpecDict,
        "status": V1IngressStatusDict,
    },
    total=False,
)
