# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1IngressStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LoadBalancerStatusDict

V1IngressStatusDict = TypedDict(
    "V1IngressStatusDict",
    {
        "loadBalancer": V1LoadBalancerStatusDict,
    },
    total=False,
)
