# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1JobSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict, V1PodTemplateSpecDict

V1JobSpecDict = TypedDict(
    "V1JobSpecDict",
    {
        "activeDeadlineSeconds": int,
        "backoffLimit": int,
        "completionMode": str,
        "completions": int,
        "manualSelector": bool,
        "parallelism": int,
        "selector": V1LabelSelectorDict,
        "suspend": bool,
        "template": V1PodTemplateSpecDict,
        "ttlSecondsAfterFinished": int,
    },
    total=False,
)
