# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LoadBalancerIngressDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1PortStatusDict

V1LoadBalancerIngressDict = TypedDict(
    "V1LoadBalancerIngressDict",
    {
        "hostname": str,
        "ip": str,
        "ports": List[V1PortStatusDict],
    },
    total=False,
)
