# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyPortDict generated type."""
from typing import TypedDict

V1NetworkPolicyPortDict = TypedDict(
    "V1NetworkPolicyPortDict",
    {
        "endPort": int,
        "port": object,
        "protocol": str,
    },
    total=False,
)
