# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1OverheadDict generated type."""
from typing import TypedDict, Dict

V1OverheadDict = TypedDict(
    "V1OverheadDict",
    {
        "podFixed": Dict[str, str],
    },
    total=False,
)
