# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1PodDisruptionBudgetSpecDict, V1PodDisruptionBudgetStatusDict

V1PodDisruptionBudgetDict = TypedDict(
    "V1PodDisruptionBudgetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1PodDisruptionBudgetSpecDict,
        "status": V1PodDisruptionBudgetStatusDict,
    },
    total=False,
)
