# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodDisruptionBudgetSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict

V1PodDisruptionBudgetSpecDict = TypedDict(
    "V1PodDisruptionBudgetSpecDict",
    {
        "maxUnavailable": object,
        "minAvailable": object,
        "selector": V1LabelSelectorDict,
    },
    total=False,
)
