# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodOSDict generated type."""
from typing import TypedDict

V1PodOSDict = TypedDict(
    "V1PodOSDict",
    {
        "name": str,
    },
    total=False,
)
