# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PortStatusDict generated type."""
from typing import TypedDict

V1PortStatusDict = TypedDict(
    "V1PortStatusDict",
    {
        "error": str,
        "port": int,
        "protocol": str,
    },
    total=False,
)
