# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RuntimeClassListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1RuntimeClassDict

V1RuntimeClassListDict = TypedDict(
    "V1RuntimeClassListDict",
    {
        "apiVersion": str,
        "items": List[V1RuntimeClassDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
