# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RollingUpdateDaemonSetDict generated type."""
from typing import TypedDict

V1RollingUpdateDaemonSetDict = TypedDict(
    "V1RollingUpdateDaemonSetDict",
    {
        "maxSurge": object,
        "maxUnavailable": object,
    },
    total=False,
)
