# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SeccompProfileDict generated type."""
from typing import TypedDict

V1SeccompProfileDict = TypedDict(
    "V1SeccompProfileDict",
    {
        "localhostProfile": str,
        "type": str,
    },
    total=False,
)
