# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetPersistentVolumeClaimRetentionPolicyDict generated type."""
from typing import TypedDict

V1StatefulSetPersistentVolumeClaimRetentionPolicyDict = TypedDict(
    "V1StatefulSetPersistentVolumeClaimRetentionPolicyDict",
    {
        "whenDeleted": str,
        "whenScaled": str,
    },
    total=False,
)
