# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import (
    V1LabelSelectorDict,
    V1PersistentVolumeClaimDict,
    V1PodTemplateSpecDict,
    V1StatefulSetPersistentVolumeClaimRetentionPolicyDict,
    V1StatefulSetUpdateStrategyDict,
)

V1StatefulSetSpecDict = TypedDict(
    "V1StatefulSetSpecDict",
    {
        "minReadySeconds": int,
        "persistentVolumeClaimRetentionPolicy": V1StatefulSetPersistentVolumeClaimRetentionPolicyDict,
        "podManagementPolicy": str,
        "replicas": int,
        "revisionHistoryLimit": int,
        "selector": V1LabelSelectorDict,
        "serviceName": str,
        "template": V1PodTemplateSpecDict,
        "updateStrategy": V1StatefulSetUpdateStrategyDict,
        "volumeClaimTemplates": List[V1PersistentVolumeClaimDict],
    },
    total=False,
)
