# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ConditionDict, V1LoadBalancerStatusDict

V1ServiceStatusDict = TypedDict(
    "V1ServiceStatusDict",
    {
        "conditions": List[V1ConditionDict],
        "loadBalancer": V1LoadBalancerStatusDict,
    },
    total=False,
)
