# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceBackendPortDict generated type."""
from typing import TypedDict

V1ServiceBackendPortDict = TypedDict(
    "V1ServiceBackendPortDict",
    {
        "name": str,
        "number": int,
    },
    total=False,
)
