# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceSpecDict generated type."""
from typing import TypedDict, Dict, List

from kubernetes_typed.client import V1ServicePortDict, V1SessionAffinityConfigDict

V1ServiceSpecDict = TypedDict(
    "V1ServiceSpecDict",
    {
        "allocateLoadBalancerNodePorts": bool,
        "clusterIP": str,
        "clusterIPs": List[str],
        "externalIPs": List[str],
        "externalName": str,
        "externalTrafficPolicy": str,
        "healthCheckNodePort": int,
        "internalTrafficPolicy": str,
        "ipFamilies": List[str],
        "ipFamilyPolicy": str,
        "loadBalancerClass": str,
        "loadBalancerIP": str,
        "loadBalancerSourceRanges": List[str],
        "ports": List[V1ServicePortDict],
        "publishNotReadyAddresses": bool,
        "selector": Dict[str, str],
        "sessionAffinity": str,
        "sessionAffinityConfig": V1SessionAffinityConfigDict,
        "type": str,
    },
    total=False,
)
