# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1UncountedTerminatedPodsDict generated type."""
from typing import TypedDict, List

V1UncountedTerminatedPodsDict = TypedDict(
    "V1UncountedTerminatedPodsDict",
    {
        "failed": List[str],
        "succeeded": List[str],
    },
    total=False,
)
