# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidationRuleDict generated type."""
from typing import TypedDict

V1ValidationRuleDict = TypedDict(
    "V1ValidationRuleDict",
    {
        "message": str,
        "rule": str,
    },
    total=False,
)
