# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionConditionDict generated type."""
import datetime
from typing import TypedDict

V1alpha1StorageVersionConditionDict = TypedDict(
    "V1alpha1StorageVersionConditionDict",
    {
        "lastTransitionTime": datetime.datetime,
        "message": str,
        "observedGeneration": int,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)
