# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1alpha1StorageVersionDict

V1alpha1StorageVersionListDict = TypedDict(
    "V1alpha1StorageVersionListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1StorageVersionDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
