# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1alpha1ServerStorageVersionDict, V1alpha1StorageVersionConditionDict

V1alpha1StorageVersionStatusDict = TypedDict(
    "V1alpha1StorageVersionStatusDict",
    {
        "commonEncodingVersion": str,
        "conditions": List[V1alpha1StorageVersionConditionDict],
        "storageVersions": List[V1alpha1ServerStorageVersionDict],
    },
    total=False,
)
