# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1StorageVersionDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1alpha1StorageVersionStatusDict

V1alpha1StorageVersionDict = TypedDict(
    "V1alpha1StorageVersionDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": object,
        "status": V1alpha1StorageVersionStatusDict,
    },
    total=False,
)
