# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2FlowSchemaListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta2FlowSchemaDict

V1beta2FlowSchemaListDict = TypedDict(
    "V1beta2FlowSchemaListDict",
    {
        "apiVersion": str,
        "items": List[V1beta2FlowSchemaDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
