# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2ResourcePolicyRuleDict generated type."""
from typing import TypedDict, List

V1beta2ResourcePolicyRuleDict = TypedDict(
    "V1beta2ResourcePolicyRuleDict",
    {
        "apiGroups": List[str],
        "clusterScope": bool,
        "namespaces": List[str],
        "resources": List[str],
        "verbs": List[str],
    },
    total=False,
)
