# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2FlowDistinguisherMethodDict generated type."""
from typing import TypedDict

V1beta2FlowDistinguisherMethodDict = TypedDict(
    "V1beta2FlowDistinguisherMethodDict",
    {
        "type": str,
    },
    total=False,
)
