# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2UserSubjectDict generated type."""
from typing import TypedDict

V1beta2UserSubjectDict = TypedDict(
    "V1beta2UserSubjectDict",
    {
        "name": str,
    },
    total=False,
)
