# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1FlowSchemaDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1FlowSchemaSpecDict, V1beta1FlowSchemaStatusDict

V1beta1FlowSchemaDict = TypedDict(
    "V1beta1FlowSchemaDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1FlowSchemaSpecDict,
        "status": V1beta1FlowSchemaStatusDict,
    },
    total=False,
)
