# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1LimitResponseDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta1QueuingConfigurationDict

V1beta1LimitResponseDict = TypedDict(
    "V1beta1LimitResponseDict",
    {
        "queuing": V1beta1QueuingConfigurationDict,
        "type": str,
    },
    total=False,
)
