# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2PriorityLevelConfigurationListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta2PriorityLevelConfigurationDict

V1beta2PriorityLevelConfigurationListDict = TypedDict(
    "V1beta2PriorityLevelConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1beta2PriorityLevelConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
