# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1NonResourcePolicyRuleDict generated type."""
from typing import TypedDict, List

V1beta1NonResourcePolicyRuleDict = TypedDict(
    "V1beta1NonResourcePolicyRuleDict",
    {
        "nonResourceURLs": List[str],
        "verbs": List[str],
    },
    total=False,
)
