# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2QueuingConfigurationDict generated type."""
from typing import TypedDict

V1beta2QueuingConfigurationDict = TypedDict(
    "V1beta2QueuingConfigurationDict",
    {
        "handSize": int,
        "queueLengthLimit": int,
        "queues": int,
    },
    total=False,
)
