# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2FlowSchemaStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta2FlowSchemaConditionDict

V1beta2FlowSchemaStatusDict = TypedDict(
    "V1beta2FlowSchemaStatusDict",
    {
        "conditions": List[V1beta2FlowSchemaConditionDict],
    },
    total=False,
)
