# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2PriorityLevelConfigurationConditionDict generated type."""
import datetime
from typing import TypedDict

V1beta2PriorityLevelConfigurationConditionDict = TypedDict(
    "V1beta2PriorityLevelConfigurationConditionDict",
    {
        "lastTransitionTime": datetime.datetime,
        "message": str,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)
