# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PriorityLevelConfigurationSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta1LimitedPriorityLevelConfigurationDict

V1beta1PriorityLevelConfigurationSpecDict = TypedDict(
    "V1beta1PriorityLevelConfigurationSpecDict",
    {
        "limited": V1beta1LimitedPriorityLevelConfigurationDict,
        "type": str,
    },
    total=False,
)
