# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1UserSubjectDict generated type."""
from typing import TypedDict

V1beta1UserSubjectDict = TypedDict(
    "V1beta1UserSubjectDict",
    {
        "name": str,
    },
    total=False,
)
