# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2PriorityLevelConfigurationReferenceDict generated type."""
from typing import TypedDict

V1beta2PriorityLevelConfigurationReferenceDict = TypedDict(
    "V1beta2PriorityLevelConfigurationReferenceDict",
    {
        "name": str,
    },
    total=False,
)
