# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2NonResourcePolicyRuleDict generated type."""
from typing import TypedDict, List

V1beta2NonResourcePolicyRuleDict = TypedDict(
    "V1beta2NonResourcePolicyRuleDict",
    {
        "nonResourceURLs": List[str],
        "verbs": List[str],
    },
    total=False,
)
