# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1EndpointHintsDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta1ForZoneDict

V1beta1EndpointHintsDict = TypedDict(
    "V1beta1EndpointHintsDict",
    {
        "forZones": List[V1beta1ForZoneDict],
    },
    total=False,
)
