# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2GroupSubjectDict generated type."""
from typing import TypedDict

V1beta2GroupSubjectDict = TypedDict(
    "V1beta2GroupSubjectDict",
    {
        "name": str,
    },
    total=False,
)
