# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ForZoneDict generated type."""
from typing import TypedDict

V1beta1ForZoneDict = TypedDict(
    "V1beta1ForZoneDict",
    {
        "name": str,
    },
    total=False,
)
