# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1FlowDistinguisherMethodDict generated type."""
from typing import TypedDict

V1beta1FlowDistinguisherMethodDict = TypedDict(
    "V1beta1FlowDistinguisherMethodDict",
    {
        "type": str,
    },
    total=False,
)
