# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2PriorityLevelConfigurationDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta2PriorityLevelConfigurationSpecDict, V1beta2PriorityLevelConfigurationStatusDict

V1beta2PriorityLevelConfigurationDict = TypedDict(
    "V1beta2PriorityLevelConfigurationDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta2PriorityLevelConfigurationSpecDict,
        "status": V1beta2PriorityLevelConfigurationStatusDict,
    },
    total=False,
)
