# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PriorityLevelConfigurationReferenceDict generated type."""
from typing import TypedDict

V1beta1PriorityLevelConfigurationReferenceDict = TypedDict(
    "V1beta1PriorityLevelConfigurationReferenceDict",
    {
        "name": str,
    },
    total=False,
)
