# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1QueuingConfigurationDict generated type."""
from typing import TypedDict

V1beta1QueuingConfigurationDict = TypedDict(
    "V1beta1QueuingConfigurationDict",
    {
        "handSize": int,
        "queueLengthLimit": int,
        "queues": int,
    },
    total=False,
)
