# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2ServiceAccountSubjectDict generated type."""
from typing import TypedDict

V1beta2ServiceAccountSubjectDict = TypedDict(
    "V1beta2ServiceAccountSubjectDict",
    {
        "name": str,
        "namespace": str,
    },
    total=False,
)
