# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1LimitedPriorityLevelConfigurationDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta1LimitResponseDict

V1beta1LimitedPriorityLevelConfigurationDict = TypedDict(
    "V1beta1LimitedPriorityLevelConfigurationDict",
    {
        "assuredConcurrencyShares": int,
        "limitResponse": V1beta1LimitResponseDict,
    },
    total=False,
)
