# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2LimitResponseDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta2QueuingConfigurationDict

V1beta2LimitResponseDict = TypedDict(
    "V1beta2LimitResponseDict",
    {
        "queuing": V1beta2QueuingConfigurationDict,
        "type": str,
    },
    total=False,
)
