# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1GroupSubjectDict generated type."""
from typing import TypedDict

V1beta1GroupSubjectDict = TypedDict(
    "V1beta1GroupSubjectDict",
    {
        "name": str,
    },
    total=False,
)
