# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ServiceAccountSubjectDict generated type."""
from typing import TypedDict

V1beta1ServiceAccountSubjectDict = TypedDict(
    "V1beta1ServiceAccountSubjectDict",
    {
        "name": str,
        "namespace": str,
    },
    total=False,
)
