# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ResourcePolicyRuleDict generated type."""
from typing import TypedDict, List

V1beta1ResourcePolicyRuleDict = TypedDict(
    "V1beta1ResourcePolicyRuleDict",
    {
        "apiGroups": List[str],
        "clusterScope": bool,
        "namespaces": List[str],
        "resources": List[str],
        "verbs": List[str],
    },
    total=False,
)
