# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CSIStorageCapacityDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict, V1ObjectMetaDict

V1beta1CSIStorageCapacityDict = TypedDict(
    "V1beta1CSIStorageCapacityDict",
    {
        "apiVersion": str,
        "capacity": str,
        "kind": str,
        "maximumVolumeSize": str,
        "metadata": V1ObjectMetaDict,
        "nodeTopology": V1LabelSelectorDict,
        "storageClassName": str,
    },
    total=False,
)
