# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2FlowSchemaDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta2FlowSchemaSpecDict, V1beta2FlowSchemaStatusDict

V1beta2FlowSchemaDict = TypedDict(
    "V1beta2FlowSchemaDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta2FlowSchemaSpecDict,
        "status": V1beta2FlowSchemaStatusDict,
    },
    total=False,
)
