# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2PolicyRulesWithSubjectsDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta2NonResourcePolicyRuleDict, V1beta2ResourcePolicyRuleDict, V1beta2SubjectDict

V1beta2PolicyRulesWithSubjectsDict = TypedDict(
    "V1beta2PolicyRulesWithSubjectsDict",
    {
        "nonResourceRules": List[V1beta2NonResourcePolicyRuleDict],
        "resourceRules": List[V1beta2ResourcePolicyRuleDict],
        "subjects": List[V1beta2SubjectDict],
    },
    total=False,
)
