# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1FlowSchemaConditionDict generated type."""
import datetime
from typing import TypedDict

V1beta1FlowSchemaConditionDict = TypedDict(
    "V1beta1FlowSchemaConditionDict",
    {
        "lastTransitionTime": datetime.datetime,
        "message": str,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)
