# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2SubjectDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta2GroupSubjectDict, V1beta2ServiceAccountSubjectDict, V1beta2UserSubjectDict

V1beta2SubjectDict = TypedDict(
    "V1beta2SubjectDict",
    {
        "group": V1beta2GroupSubjectDict,
        "kind": str,
        "serviceAccount": V1beta2ServiceAccountSubjectDict,
        "user": V1beta2UserSubjectDict,
    },
    total=False,
)
