# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PriorityLevelConfigurationListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta1PriorityLevelConfigurationDict

V1beta1PriorityLevelConfigurationListDict = TypedDict(
    "V1beta1PriorityLevelConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1PriorityLevelConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
