# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CSIStorageCapacityListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta1CSIStorageCapacityDict

V1beta1CSIStorageCapacityListDict = TypedDict(
    "V1beta1CSIStorageCapacityListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1CSIStorageCapacityDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
