# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2FlowSchemaSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta2FlowDistinguisherMethodDict, V1beta2PolicyRulesWithSubjectsDict, V1beta2PriorityLevelConfigurationReferenceDict

V1beta2FlowSchemaSpecDict = TypedDict(
    "V1beta2FlowSchemaSpecDict",
    {
        "distinguisherMethod": V1beta2FlowDistinguisherMethodDict,
        "matchingPrecedence": int,
        "priorityLevelConfiguration": V1beta2PriorityLevelConfigurationReferenceDict,
        "rules": List[V1beta2PolicyRulesWithSubjectsDict],
    },
    total=False,
)
