# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PriorityLevelConfigurationDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1PriorityLevelConfigurationSpecDict, V1beta1PriorityLevelConfigurationStatusDict

V1beta1PriorityLevelConfigurationDict = TypedDict(
    "V1beta1PriorityLevelConfigurationDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1PriorityLevelConfigurationSpecDict,
        "status": V1beta1PriorityLevelConfigurationStatusDict,
    },
    total=False,
)
