# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta2PriorityLevelConfigurationStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta2PriorityLevelConfigurationConditionDict

V1beta2PriorityLevelConfigurationStatusDict = TypedDict(
    "V1beta2PriorityLevelConfigurationStatusDict",
    {
        "conditions": List[V1beta2PriorityLevelConfigurationConditionDict],
    },
    total=False,
)
