# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1FlowSchemaSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta1FlowDistinguisherMethodDict, V1beta1PolicyRulesWithSubjectsDict, V1beta1PriorityLevelConfigurationReferenceDict

V1beta1FlowSchemaSpecDict = TypedDict(
    "V1beta1FlowSchemaSpecDict",
    {
        "distinguisherMethod": V1beta1FlowDistinguisherMethodDict,
        "matchingPrecedence": int,
        "priorityLevelConfiguration": V1beta1PriorityLevelConfigurationReferenceDict,
        "rules": List[V1beta1PolicyRulesWithSubjectsDict],
    },
    total=False,
)
