# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1FlowSchemaStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta1FlowSchemaConditionDict

V1beta1FlowSchemaStatusDict = TypedDict(
    "V1beta1FlowSchemaStatusDict",
    {
        "conditions": List[V1beta1FlowSchemaConditionDict],
    },
    total=False,
)
