# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2CrossVersionObjectReferenceDict generated type."""
from typing import TypedDict

V2CrossVersionObjectReferenceDict = TypedDict(
    "V2CrossVersionObjectReferenceDict",
    {
        "apiVersion": str,
        "kind": str,
        "name": str,
    },
    total=False,
)
