# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ExternalMetricSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2MetricIdentifierDict, V2MetricTargetDict

V2ExternalMetricSourceDict = TypedDict(
    "V2ExternalMetricSourceDict",
    {
        "metric": V2MetricIdentifierDict,
        "target": V2MetricTargetDict,
    },
    total=False,
)
