# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HPAScalingPolicyDict generated type."""
from typing import TypedDict

V2HPAScalingPolicyDict = TypedDict(
    "V2HPAScalingPolicyDict",
    {
        "periodSeconds": int,
        "type": str,
        "value": int,
    },
    total=False,
)
