# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerBehaviorDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2HPAScalingRulesDict

V2HorizontalPodAutoscalerBehaviorDict = TypedDict(
    "V2HorizontalPodAutoscalerBehaviorDict",
    {
        "scaleDown": V2HPAScalingRulesDict,
        "scaleUp": V2HPAScalingRulesDict,
    },
    total=False,
)
