# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerConditionDict generated type."""
import datetime
from typing import TypedDict

V2HorizontalPodAutoscalerConditionDict = TypedDict(
    "V2HorizontalPodAutoscalerConditionDict",
    {
        "lastTransitionTime": datetime.datetime,
        "message": str,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)
