# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V2CrossVersionObjectReferenceDict, V2HorizontalPodAutoscalerBehaviorDict, V2MetricSpecDict

V2HorizontalPodAutoscalerSpecDict = TypedDict(
    "V2HorizontalPodAutoscalerSpecDict",
    {
        "behavior": V2HorizontalPodAutoscalerBehaviorDict,
        "maxReplicas": int,
        "metrics": List[V2MetricSpecDict],
        "minReplicas": int,
        "scaleTargetRef": V2CrossVersionObjectReferenceDict,
    },
    total=False,
)
