# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2HorizontalPodAutoscalerDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V2HorizontalPodAutoscalerSpecDict, V2HorizontalPodAutoscalerStatusDict

V2HorizontalPodAutoscalerDict = TypedDict(
    "V2HorizontalPodAutoscalerDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V2HorizontalPodAutoscalerSpecDict,
        "status": V2HorizontalPodAutoscalerStatusDict,
    },
    total=False,
)
