# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricIdentifierDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict

V2MetricIdentifierDict = TypedDict(
    "V2MetricIdentifierDict",
    {
        "name": str,
        "selector": V1LabelSelectorDict,
    },
    total=False,
)
