# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricTargetDict generated type."""
from typing import TypedDict

V2MetricTargetDict = TypedDict(
    "V2MetricTargetDict",
    {
        "averageUtilization": int,
        "averageValue": str,
        "type": str,
        "value": str,
    },
    total=False,
)
