# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2MetricValueStatusDict generated type."""
from typing import TypedDict

V2MetricValueStatusDict = TypedDict(
    "V2MetricValueStatusDict",
    {
        "averageUtilization": int,
        "averageValue": str,
        "value": str,
    },
    total=False,
)
