# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ObjectMetricSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2CrossVersionObjectReferenceDict, V2MetricIdentifierDict, V2MetricTargetDict

V2ObjectMetricSourceDict = TypedDict(
    "V2ObjectMetricSourceDict",
    {
        "describedObject": V2CrossVersionObjectReferenceDict,
        "metric": V2MetricIdentifierDict,
        "target": V2MetricTargetDict,
    },
    total=False,
)
