# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ObjectMetricStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2CrossVersionObjectReferenceDict, V2MetricIdentifierDict, V2MetricValueStatusDict

V2ObjectMetricStatusDict = TypedDict(
    "V2ObjectMetricStatusDict",
    {
        "current": V2MetricValueStatusDict,
        "describedObject": V2CrossVersionObjectReferenceDict,
        "metric": V2MetricIdentifierDict,
    },
    total=False,
)
