# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2PodsMetricSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2MetricIdentifierDict, V2MetricTargetDict

V2PodsMetricSourceDict = TypedDict(
    "V2PodsMetricSourceDict",
    {
        "metric": V2MetricIdentifierDict,
        "target": V2MetricTargetDict,
    },
    total=False,
)
