# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2ResourceMetricSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2MetricTargetDict

V2ResourceMetricSourceDict = TypedDict(
    "V2ResourceMetricSourceDict",
    {
        "name": str,
        "target": V2MetricTargetDict,
    },
    total=False,
)
