# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2ContainerResourceMetricSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2beta2MetricTargetDict

V2beta2ContainerResourceMetricSourceDict = TypedDict(
    "V2beta2ContainerResourceMetricSourceDict",
    {
        "container": str,
        "name": str,
        "target": V2beta2MetricTargetDict,
    },
    total=False,
)
