# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2ContainerResourceMetricStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2beta2MetricValueStatusDict

V2beta2ContainerResourceMetricStatusDict = TypedDict(
    "V2beta2ContainerResourceMetricStatusDict",
    {
        "container": str,
        "current": V2beta2MetricValueStatusDict,
        "name": str,
    },
    total=False,
)
