# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1ContainerResourceMetricStatusDict generated type."""
from typing import TypedDict

V2beta1ContainerResourceMetricStatusDict = TypedDict(
    "V2beta1ContainerResourceMetricStatusDict",
    {
        "container": str,
        "currentAverageUtilization": int,
        "currentAverageValue": str,
        "name": str,
    },
    total=False,
)
