# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1ContainerResourceMetricSourceDict generated type."""
from typing import TypedDict

V2beta1ContainerResourceMetricSourceDict = TypedDict(
    "V2beta1ContainerResourceMetricSourceDict",
    {
        "container": str,
        "name": str,
        "targetAverageUtilization": int,
        "targetAverageValue": str,
    },
    total=False,
)
