# Code generated by `stubgen`. DO NOT EDIT.
from kubernetes import client as client, config as config
from kubernetes.leaderelection import electionconfig as electionconfig, leaderelection as leaderelection
from kubernetes.leaderelection.resourcelock.configmaplock import ConfigMapLock as ConfigMapLock
from typing import Any

candidate_id: Any
lock_name: str
lock_namespace: str

def example_func() -> None: ...
