# Code generated by `stubgen`. DO NOT EDIT.
import unittest
from .ws_client import get_websocket_url as get_websocket_url, websocket_proxycare as websocket_proxycare
from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

def dictval(dict: Any, key: Any, default: Optional[Any] = ...): ...

class WSClientTest(unittest.TestCase):
    def test_websocket_client(self) -> None: ...
    def test_websocket_proxycare(self) -> None: ...
